FROM python:3.9-slim

WORKDIR /app

# Copy application source
COPY app/ /app/

# Copy version file
COPY version.txt /app/version.txt

# Copy build metadata generated by Jenkins
COPY build_info.json /app/build_info.json

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]