from flask import Flask, render_template, jsonify
import datetime
import json
from prometheus_flask_exporter import PrometheusMetrics

app = Flask(__name__)

# Prometheus metrics — exposed at /metrics
metrics = PrometheusMetrics(app)
metrics.info('app_info', 'DevOps Dashboard Info', version='1.0')


def get_build_info():
    """Read build metadata generated by Jenkins."""
    try:
        with open("build_info.json", "r") as f:
            return json.load(f)
    except Exception:
        return {
            "build_number": "N/A",
            "git_commit":   "unknown",
            "git_branch":   "unknown",
            "build_time":   "N/A",
            "status":       "unknown",
            "failed_stage": ""
        }


def get_version():
    try:
        with open("version.txt", "r") as f:
            return f.read().strip()
    except Exception:
        return "1.0"


@app.route("/")
def dashboard():
    build_info = get_build_info()
    version    = get_version()
    uptime     = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    logs     = get_logs()
    pipeline = get_pipeline_stages(build_info)
    return render_template("dashboard.html", build_info=build_info, version=version, uptime=uptime, pipeline=pipeline, logs=logs)


@app.route("/health")
def health():
    """Health check endpoint used by Jenkins verify stage."""
    return jsonify({"status": "ok", "time": datetime.datetime.now().isoformat()}), 200


@app.route("/api/info")
def api_info():
    """JSON endpoint for external monitoring."""
    info = get_build_info()
    info["version"]     = get_version()
    info["server_time"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return jsonify(info)


def get_pipeline_stages(build_info):
    stages = ["Clone", "Test", "Build Info", "Build", "Deploy", "Live"]

    failed_stage = build_info.get("failed_stage")
    status = build_info.get("status")

    pipeline = []
    after_fail = False

    for stage in stages:
        if stage == failed_stage:
            pipeline.append({"name": stage, "state": "failed"})
            after_fail = True
        elif after_fail:
            pipeline.append({"name": stage, "state": "skipped"})
        elif stage == "Live" and status == "success":
            pipeline.append({"name": stage, "state": "running"})
        else:
            pipeline.append({"name": stage, "state": "passed"})

    return pipeline

def get_logs():
    try:
        with open("logs.txt", "r") as f:
            return f.readlines()
    except:
        return ["No logs available"]


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)