from flask import Flask, render_template, jsonify
import datetime
import json
import os

app = Flask(__name__)


def get_build_info():
    """Read build metadata generated by Jenkins during the pipeline."""
    try:
        with open("build_info.json", "r") as f:
            return json.load(f)
    except Exception:
        return {
            "build_number": "N/A",
            "git_commit": "unknown",
            "git_branch": "unknown",
            "build_time": "N/A",
            "status": "unknown"
        }


def get_version():
    """Read app version from version.txt."""
    try:
        with open("version.txt", "r") as f:
            return f.read().strip()
    except Exception:
        return "1.0"


@app.route("/")
def dashboard():
    build_info = get_build_info()
    version = get_version()
    uptime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return render_template(
        "dashboard.html",
        build_info=build_info,
        version=version,
        uptime=uptime
    )


@app.route("/api/info")
def api_info():
    """JSON endpoint — useful for health checks or external monitoring."""
    build_info = get_build_info()
    build_info["version"] = get_version()
    build_info["server_time"] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    build_info["status"] = "running"
    return jsonify(build_info)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)